### PR TITLE
INF-60: Open Access Website Workflow

### PR DESCRIPTION
**Pull request by jdddog**
This PR adds a workflow that generates the data for the COKI Open Access website, copies the data to the websites static folder, builds the website and then deploys it with Cloudflare.

### CODE REVIEW

**Review by aroelo — CHANGES_REQUESTED** [review]
Hi @jdddog,

I've just added a small comment about the variables/connections.
It might also be good to add a readthedocs file with some info on the website_folder variable and how to create the cloudflare api connection.

Also, before we split the repository for the different workflow projects we would add new variables/connections in the AirflowVars & AirflowConns classes in airflow_utils.py.
What is the recommended approach now that we have split the repositories?
Should we only include those variables/connections that are used with templates or utils inside the observatory-platform, so remove ORCID, OAPEN IRUS UK, etc.
Or do we still add any new variables/connections here, like the ones used in this workflow?

And just curious myself, what is the website_folder and what do those build & deploy scripts look like, is that in a different repository somewhere?

**Comment by jdddog** [comment]
> Hi @jdddog,
> 
> I've just added a small comment about the variables/connections. It might also be good to add a readthedocs file with some info on the website_folder variable and how to create the cloudflare api connection.

Thanks Aniek, will do.

> 
> Also, before we split the repository for the different workflow projects we would add new variables/connections in the AirflowVars & AirflowConns classes in airflow_utils.py. What is the recommended approach now that we have split the repositories? Should we only include those variables/connections that are used with templates or utils inside the observatory-platform, so remove ORCID, OAPEN IRUS UK, etc. Or do we still add any new variables/connections here, like the ones used in this workflow?

It would be good to put the workflow specific variables and connections into each workflow as class variables. We should remove the others from the observatory platform.

> 
> And just curious myself, what is the website_folder and what do those build & deploy scripts look like, is that in a different repository somewhere?

The website folder is the folder where the static website is cloned into. The build script builds the website and the deploy script deploys it to Cloudflare. Yeah I'll be making a project soon, with the web application for the open access dashboard which will contain these scripts.

**Comment by jdddog** [comment]
I've made those changes Aniek. I've remove the need for the website folder being specified as an Airflow variable.

**Comment by aroelo** [comment]
> I've made those changes Aniek. I've removed the need for the website folder being specified as an Airflow variable.

Thanks @jdddog, looks good to me!

**Review by aroelo — APPROVED** [review]

**Pull request merged**
